[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "detecti-cli"
version = "2.3.0"
description = "Legacy package for DetecTI-CLI. Please install reconhound instead."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "reconhound>=3.0.0"
]

[project.scripts]
detecti-cli = "detecti_cli_legacy:main"

[tool.hatch.build.targets.wheel]
packages = ["."]
